all: patch shell xor target

patch: patch.cpp
	c++ patch.cpp -o patch -O0

shell: shell.cpp
	c++ shell.cpp -o shell

xor: xor.cpp
	c++ xor.cpp -o xor

target: target.cpp
	c++ target.cpp -o target -O0
